# Generated by Django 3.1.4 on 2020-12-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeruser',
            name='role',
            field=models.CharField(choices=[('PR', 'Processor'), ('SV', 'Supervisor'), ('AD', 'Admin'), ('EX', 'External')], default=None, max_length=2),
        ),
    ]
