# Generated by Django 3.1.4 on 2020-12-26 20:07

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import document_units.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20201221_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('data', document_units.models.RawJSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='projects.project')),
            ],
            options={
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='DocumentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(default='no text provided')),
                ('document_data', document_units.models.RawJSONField(default=dict, null=True)),
                ('document_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/documents'), upload_to='')),
                ('document_format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_units.documentformat')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
    ]
