# Generated by Django 3.1.4 on 2020-12-26 20:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformat',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
